import { header } from './elements/header.js';
import { menu } from './elements/menu.js';
import { lenis } from './elements/lenis.js';
import { gsapme } from './elements/gsap';
import { scrolltriggerme } from './elements/scrollTrigger.js';
import { anime } from './elements/animate.js';
import { counter } from './elements/counter.js';
import { youtube, vimeo } from './elements/popup.js';
import { testimonialSwiper, valuePropsSwiper } from './elements/swiper.js';
import { accordion } from './elements/accordion.js';
import { asSeen } from './elements/asSlider.js';
import { slickme } from './elements/customSlick.js';
import { stickme } from './elements/sticksy.js';
import { cards } from './elements/swipecards.js';
import { spyScroll } from './elements/spyScroll.js';
import { categories } from './elements/categories.js';

document.addEventListener('DOMContentLoaded', () => {
  header.init();
  menu.init();
  lenis.init();
  gsapme.init();
  scrolltriggerme.init();
  counter.init();
  anime.init();
  youtube.init();
  vimeo.init();
  testimonialSwiper.init();
  valuePropsSwiper.init();
  accordion.init();
  asSeen.slider();
  spyScroll.init();
  slickme.init();
  stickme.init();
  cards.init();
  categories.init();
});
